export const products = [
    {
        id: 1,
        imageSrc: 'https://content2.rozetka.com.ua/goods/images/big/319651033.jpg',
        title: 'Ноутбук Acer Aspire 5',
        seller: 'Acer Official Store',
        price: '25 000',
        brand: 'Acer',
    },
    {
        id: 2,
        imageSrc: 'https://content.rozetka.com.ua/goods/images/big/191407059.jpg',
        title: 'Ноутбук Dell Inspiron 15',
        seller: 'Rozetka',
        price: '30 000',
        brand: 'Dell',
    },
    {
        id: 3,
        imageSrc: 'https://content2.rozetka.com.ua/goods/images/big_tile/345234211.jpg',
        title: 'Ноутбук HP Pavilion',
        seller: 'HP Store',
        price: '28 000',
        brand: 'HP',
    },
    {
        id: 4,
        imageSrc: 'https://content.rozetka.com.ua/goods/images/big/333207936.jpg',
        title: 'Ноутбук Lenovo ThinkPad',
        seller: 'Lenovo Official Store',
        price: '35 000',
        brand: 'Lenovo',
    },
    {
        id: 5,
        imageSrc: 'https://content1.rozetka.com.ua/goods/images/big/370846833.jpg',
        title: 'Ноутбук ASUS VivoBook',
        seller: 'ASUS Store',
        price: '32 000',
        brand: 'ASUS',
    },
    {
        id: 6,
        imageSrc: 'https://content.rozetka.com.ua/goods/images/original/215770075.jpg',
        title: 'Ноутбук Apple MacBook Air',
        seller: 'Apple Store',
        price: '60 000',
        brand: 'Apple',
    },
    {
        id: 7,
        imageSrc: 'https://content1.rozetka.com.ua/goods/images/big/159854194.jpg',
        title: 'Ноутбук MSI Gaming',
        seller: 'MSI Official Store',
        price: '45 000',
        brand: 'MSI',
    },
    {
        id: 8,
        imageSrc: 'https://content2.rozetka.com.ua/goods/images/big/255377372.jpg',
        title: 'Ноутбук Sony VAIO',
        seller: 'Sony Store',
        price: '40 000',
        brand: 'Sony',
    },
    {
        id: 9,
        imageSrc: 'https://content1.rozetka.com.ua/goods/images/big/45456721.jpg',
        title: 'Ноутбук Toshiba Satellite',
        seller: 'Rozetka',
        price: '27 000',
        brand: 'Toshiba',
    },
    {
        id: 10,
        imageSrc: 'https://content2.rozetka.com.ua/goods/images/big/260094774.jpg',
        title: 'Ноутбук Samsung Galaxy Book',
        seller: 'Samsung Store',
        price: '38 000',
        brand: 'Samsung',
    },
    {
        id: 11,
        imageSrc: 'https://content1.rozetka.com.ua/goods/images/big/372638471.jpg',
        title: 'Ноутбук Dell XPS 13',
        seller: 'Dell Store',
        price: '50 000',
        brand: 'Dell',
    },
    {
        id: 12,
        imageSrc: 'https://content.rozetka.com.ua/goods/images/big_tile/231370289.jpg',
        title: 'Ноутбук Lenovo Yoga C940',
        seller: 'Lenovo Official Store',
        price: '55 000',
        brand: 'Lenovo',
    },
    {
        id: 13,
        imageSrc: 'https://content.rozetka.com.ua/goods/images/big/322993334.jpg',
        title: 'Ноутбук ASUS ROG Zephyrus',
        seller: 'Rozetka',
        price: '70 000',
        brand: 'ASUS',
    },
    {
        id: 14,
        imageSrc: 'https://content2.rozetka.com.ua/goods/images/big/140301642.jpg',
        title: 'Ноутбук HP Spectre x360',
        seller: 'HP Store',
        price: '65 000',
        brand: 'HP',
    },
    {
        id: 15,
        imageSrc: 'https://content.rozetka.com.ua/goods/images/big/260237211.jpg',
        title: 'Ноутбук Acer Predator Helios',
        seller: 'Rozetka',
        price: '75 000',
        brand: 'Acer',
    },
]
